on: push
name: analysis-publisher/ci
jobs:
  build:
    name: analysis-publisher/ci/analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - run: ./gradlew check
    - name: Publish coverage
      uses: docker://node
      env: #required
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        entrypoint: npx
        args: codecov
    - name: Publish analysis results
      run: ./gradlew run --args="--report-type=checkstyle --path=**/checkstyle/*.xml --report-type=spotbugs --path=**/spotbugs/*.xml --publisher=github_check"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}